main: su.nightexpress.combatpets.PetsPlugin
name: CombatPets
version: '${project.version}'
author: NightExpress
description: Customizable pets with many cool features!
depend:
  - nightcore
softdepend:
  - MythicMobs
  - PlaceholderAPI
  - EconomyBridge
api-version: 1.20